version: '3.7'

networks:
  default:
    driver: bridge

services:
  jest-puppeteer:
    build:
      context: .
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
    image: cybersamx/jest-puppeteer
    networks:
      - default
